#pragma once
#include <string>

#define ID				string("ID")
#define ASSIGN			string("ASSIGN")
#define INTEGER_CONST	string("INTEGER_CONST")
#define REAL_CONST		string("REAL_CONST")
#define PLUS			string("PLUS")
#define MINUS			string("MINUS")
#define MUL				string("MUL")
#define INTEGER_DIV		string("INTEGER_DIV")
#define FLOAT_DIV		string("FLOAT_DIV")
#define MOD				string("MOD")
#define POW				string("POW")
#define LPAREN			string("(")
#define RPAREN			string(")")
#define LOP				string("[")
#define ROP				string("]")
#define EOF				string("EOF")
#define IF				string("IF")
#define ELSE			string("ELSE")
#define LT				string("<")
#define LE				string("<=")
#define GT				string(">")
#define GE				string(">=")
#define EQUAL			string("EQUAL")
#define PLUS_ASSIGN		string("+=")
#define MINUS_ASSIGN	string("-=")
#define MUL_ASSIGN		string("*=")
#define DIV_ASSIGN		string("/=")
#define SIN				string("SIN")
#define COS				string("COS")
#define TAN				string("TAN")
#define COT				string("COT")
#define LG				string("LG")
#define LN				string("LN")
#define PI				string("PI")
#define EXP				string("EXP")